function tbwl(){
const ctwl = [
             "Prison Playbook",
             "Mr. Sunshine",
             "Eulachacha Waikiki",
             "Move to Heaven",
             "Flower of Evil",
             "Mr. Queen",
             "Mouse",
             "D.P.",
             "The Devil Judge",
             "Ghost Doctor",
             "Happiness",
             "Our Blues",
             "Duty After School: Part 1",
             "Under the Queen's Umbrella",
             "Tale of the Nine-Tailed 1938",
             "Death's Game",
             "Twinkling Watermelon",
             "Death's Game Part 2",
             "Hormones",
             "Descendants of the Sun",
             "Signal",
             "Save Me",
             "Kingdom",
             "The Gifted",
             "Partners for Justice",
             "The Guest",
             "Vagabond",
             "Girl From Nowhere",
             "Partners for Justice Season 2",
             "Doctor John",
             "Imawa no Kuni no Alice",
             "Let's Fight Ghost",
             "The Gifted Graduation",
             "It's Okay to Not Be Okay",
             "Memorist",
             "365: Repeat the Year",
             "Search",
             "Taxi Driver",
             "All of Us Are Dead",
             "Beyond Evil",
             "Snowdrop",
             "Law School",
             "Reborn Rich",
             "Juvenile Justice",
             "The Veil",
             "Imawa no Kuni no Alice Season 2",
             "Police University",
             "One Ordinary Day",
             "Blue Birthday",
             "Tomorrow",
             "Through the Darkness",
             "My Man Is Cupid",
             "Sweet Home Season 2",
             "Military Prosecutor Doberman",
             "The First Responders",
             "Don't Touch My Gang",
             "D.P. Season 2",
             "Home School",
             "The Eclipse",
             "My School President",
             "Revenge of Others",
             "Thai Cave Rescue",
             "Night Has Come",
             "The Killing Vote",
             "Enigma",
             "Marry My Husband",
             "Pending Train: 8:23, Ashita Kimi to",
             "I Hear Your Voice",
             "Doctor Stranger",
             "Hormones Season 2",
             "Healer",
             "Pinocchio",
             "Who Are You: School 2015",
             "Death Note",
             "D-Day",
             "Hormones Season 3",
             "Moorim School",
             "Doctors",
             "W: Two Worlds",
             "Goblin",
             "Bring It On, Ghost",
             "The Legend of the Blue Sea",
             "The K2",
             "Voice",
             "Solomon's Perjury",
             "Introverted Boss",
             "While You Were Sleeping",
             "Tunnel",
             "Criminal Minds",
             "Queen of Mystery",
             "Hospital Ship",
             "A Korean Odyssey",
             "Queen of Mystery Season 2",
             "Witch's Court",
             "Voice Season 2",
             "Lawless Lawyer",
             "The Hymn of Death",
             "Player",
             "Voice Season 3: City of Accomplices",
             "Doctor Prisoner",
             "He Is Psychometric",
             "Blacklist",
             "Kingdom Season 2",
             "Designated Survivor: 60 Days",
             "Voice",
             "Bad Genius",
             "The Lies Within",
             "Itaewon Class",
             "Class of Lies",
             "Sweet Home",
             "Extracurricular",
             "Alice",
             "2gether",
             "Squid Game",
             "Sisyphus: The Myth",
             "Who Are You",
             "Tunnel",
             "Island",
             "Train",
             "Tale of the Nine-Tailed",
             "Awaken",
             "MIU 404",
             "Kairos",
             "The Miracle of Teddy Bear",
             "Island Part 2",
             "The Uncanny Counter",
             "I'm Tee, Me Too",
             "My Name",
             "Girl From Nowhere Season 2",
             "Voice Season 4: Judgment Hour",
             "55:15 Never Too Late",
             "Bad Buddy",
             "Rookie Cops",
             "Again My Life",
             "The Golden Spoon",
             "The Comments",
             "Doctor Lawyer",
             "Get Rich",
             "Left on Read",
             "The Days",
             "Double Savage",
             "Midnight Museum",
             "School 2013",
             "The Heirs",
             "My Love from the Star",
             "You're All Surrounded",
             "Hi! School - Love On",
             "Liar Game",
             "ThirTEEN Terrors",
             "Hidden Identity",
             "Uncontrollably Fond",
             "Local Hero",
             "Nightmare Teacher",
             "Cinderella and the Four Knights",
             "Fight for My Way",
             "School 2017",
             "My Engineer",
             "Memories of the Alhambra",
             "Zero: Ikkaku Senkin Game",
             "Fleet of Time",
             "Melting Me Softly",
             "Crash Landing on You",
             "Times",
             "Kimi to Sekai ga Owaru Hi ni",
             "Kimi to Sekai ga Owaru Hi ni Season 2",
             "Red Eyes: Kanshi Sousa-han",
             "Melancholia",
             "Kimi to Sekai ga Owaru Hi ni Season 3",
             "Connect",
             "Black Knight",
             "Dirty Laundry",
             "School Tales the Series",
             "City Hunter",
             "Boys Over Flowers",
             "Blood",
             "Princess Hours",
             "Abyss",
             "The Stranded",
             "Rugal",
             "School 2021",
             "Start-Up",
             "Dark Hole",
             "Tonhon Chonlatee",
             "Money Heist: Korea - Joint Economic Area - Part 1",
             "So Not Worth It",
             "Once Upon a Small Town",
             "Remember Me",
             "Duty After School: Part 2",
             "The School Nurse Files",
             "The Silent Sea",
             "Monstrous",
             "The Kidnapping Day",
             "Gyeongseong Creature",
             "Decoy: Part 1",
             "Hospital Playlist",
             "Vincenzo",
             "The Glory",
             "Taxi Driver Season 2",
             "Dr. Romantic",
             "18 Again",
             "Revenant",
             "Chicago Typewriter",
             "Big Mouth",
             "Bad and Crazy",
             "See You in My 19th Life",
             "The Sound of Your Heart",
             "WATCHER",
             "The Uncanny Counter Season 2: Counter Punch",
             "King the Land",
             "My Demon",
             "Are You Human Too?",
             "Kill It",
             "Diary of a Prosecutor",
             "Tell Me What You Saw",
             "Our Blooming Youth",
             "Café Minamdang",
             "Miraculous Brothers",
             "Money Game",
             "Numbers",
             "Longing for You",
             "Lies Hidden in My Garden",
             "Delete",
             "Hometown",
             "Heartbeat",
             "UMG",
             "Full House",
             "About Time",
             "Life",
             "Eulachacha Waikiki Season 2",
             "Jirisan",
             "Yumi's Cells",
             "Crazy Love",
             "Celebrity",
             "Cheer Up",
             "The Heavenly Idol",
             "Loneliness Society",
             
             
             ];

const ccwl = [
             "South Korea",
             "South Korea",
             "South Korea",
             "South Korea",
             "South Korea",
             "South Korea",
             "South Korea",
             "South Korea",
             "South Korea",
             "South Korea",
             "South Korea",
             "South Korea",
             "South Korea",
             "South Korea",
             "South Korea",
             "South Korea",
             "South Korea",
             "South Korea",
             "Thailand",
             "South Korea",
             "South Korea",
             "South Korea",
             "South Korea",
             "Thailand",
             "South Korea",
             "South Korea",
             "South Korea",
             "Thailand",
             "South Korea",
             "South Korea",
             "Japan",
             "Thailand",
             "Thailand",
             "South Korea",
             "South Korea",
             "South Korea",
             "South Korea",
             "South Korea",
             "South Korea",
             "South Korea",
             "South Korea",
             "South Korea",
             "South Korea",
             "South Korea",
             "South Korea",
             "Japan",
             "South Korea",
             "South Korea",
             "South Korea",
             "South Korea",
             "South Korea",
             "South Korea",
             "South Korea",
             "South Korea",
             "South Korea",
             "Thailand",
             "South Korea",
             "Thailand",
             "Thailand",
             "Thailand",
             "South Korea",
             "Thailand",
             "South Korea",
             "South Korea",
             "Thailand",
             "South Korea",
             "Japan",
             "South Korea",
             "South Korea",
             "Thailand",
             "South Korea",
             "South Korea",
             "South Korea",
             "Japan",
             "South Korea",
             "Thailand",
             "South Korea",
             "South Korea",
             "South Korea",
             "South Korea",
             "South Korea",
             "South Korea",
             "South Korea",
             "South Korea",
             "South Korea",
             "South Korea",
             "South Korea",
             "South Korea",
             "South Korea",
             "South Korea",
             "South Korea",
             "South Korea",
             "South Korea",
             "South Korea",
             "South Korea",
             "South Korea",
             "South Korea",
             "South Korea",
             "South Korea",
             "South Korea",
             "South Korea",
             "Thailand",
             "South Korea",
             "South Korea",
             "Thailand",
             "Thailand",
             "South Korea",
             "South Korea",
             "South Korea",
             "South Korea",
             "South Korea",
             "South Korea",
             "Thailand",
             "South Korea",
             "South Korea",
             "Thailand",
             "Thailand",
             "South Korea",
             "South Korea",
             "South Korea",
             "South Korea",
             "Japan",
             "South Korea",
             "Thailand",
             "South Korea",
             "South Korea",
             "Thailand",
             "South Korea",
             "Thailand",
             "South Korea",
             "Thailand",
             "Thailand",
             "South Korea",
             "South Korea",
             "South Korea",
             "Thailand",
             "South Korea",
             "Thailand",
             "Hong Kong",
             "Japan",
             "Thailand",
             "Thailand",
             "South Korea",
             "South Korea",
             "South Korea",
             "South Korea",
             "South Korea",
             "South Korea",
             "Thailand",
             "South Korea",
             "South Korea",
             "South Korea",
             "South Korea",
             "South Korea",
             "South Korea",
             "South Korea",
             "Thailand",
             "South Korea",
             "Japan",
             "Thailand",
             "South Korea",
             "South Korea",
             "South Korea",
             "Japan",
             "Japan",
             "Japan",
             "South Korea",
             "Japan",
             "South Korea",
             "South Korea",
             "Thailand",
             "Thailand",
             "South Korea",
             "South Korea",
             "South Korea",
             "Thailand",
             "South Korea",
             "Thailand",
             "South Korea",
             "South Korea",
             "South Korea",
             "South Korea",
             "Thailand",
             "South Korea",
             "South Korea",
             "South Korea",
             "Thailand",
             "South Korea",
             "South Korea",
             "South Korea",
             "South Korea",
             "South Korea",
             "South Korea",
             "South Korea",
             "South Korea",
             "South Korea",
             "South Korea",
             "South Korea",
             "South Korea",
             "South Korea",
             "South Korea",
             "South Korea",
             "South Korea",
             "South Korea",
             "South Korea",
             "South Korea",
             "South Korea",
             "South Korea",
             "South Korea",
             "South Korea",
             "South Korea",
             "South Korea",
             "South Korea",
             "South Korea",
             "South Korea",
             "South Korea",
             "South Korea",
             "South Korea",
             "South Korea",
             "South Korea",
             "South Korea",
             "Thailand",
             "South Korea",
             "South Korea",
             "Thailand",
             "South Korea",
             "South Korea",
             "South Korea",
             "South Korea",
             "South Korea",
             "South Korea",
             "South Korea",
             "South Korea",
             "South Korea",
             "South Korea",
             "Thailand",
             
             
             ];

const cywl = [
             "2017",
             "2018",
             "2018",
             "2021",
             "2020",
             "2020",
             "2021",
             "2021",
             "2021",
             "2022",
             "2021",
             "2022",
             "2023",
             "2022",
             "2023",
             "2023",
             "2023",
             "2024",
             "2013",
             "2016",
             "2016",
             "2017",
             "2019",
             "2018",
             "2018",
             "2018",
             "2019",
             "2018",
             "2019",
             "2019",
             "2020",
             "2021",
             "2020",
             "2020",
             "2020",
             "2020",
             "2020",
             "2021",
             "2022",
             "2021",
             "2021",
             "2021",
             "2022",
             "2022",
             "2021",
             "2022",
             "2021",
             "2021",
             "2021",
             "2022",
             "2022",
             "2023",
             "2023",
             "2022",
             "2022",
             "2023",
             "2023",
             "2023",
             "2022",
             "2022",
             "2022",
             "2022",
             "2023",
             "2023",
             "2023",
             "2024",
             "2023",
             "2013",
             "2014",
             "2014",
             "2014",
             "2014",
             "2015",
             "2015",
             "2015",
             "2015",
             "2016",
             "2016",
             "2016",
             "2016",
             "2016",
             "2016",
             "2016",
             "2017",
             "2016",
             "2017",
             "2017",
             "2017",
             "2017",
             "2017",
             "2017",
             "2017",
             "2018",
             "2017",
             "2018",
             "2018",
             "2018",
             "2018",
             "2019",
             "2019",
             "2019",
             "2019",
             "2020",
             "2019", 
             "2019",
             "2020",
             "2019",
             "2020",
             "2019",
             "2020",
             "2020",
             "2020",
             "2020",
             "2021",
             "2021",
             "2020",
             "2019",
             "2022",
             "2020",
             "2020",
             "2020",
             "2020",
             "2020",
             "2022",
             "2023",
             "2020",
             "2020",
             "2021",
             "2021",
             "2021",
             "2021",
             "2021",
             "2022",
             "2022",
             "2022",
             "2021",
             "2022",
             "2023",
             "2023",
             "2023",
             "2023",
             "2023",
             "2012",
             "2013",
             "2013",
             "2014",
             "2014",
             "2014",
             "2014",
             "2015",
             "2016",
             "2016",
             "2016",
             "2016",
             "2017",
             "2017",
             "2020",
             "2018",
             "2018",
             "2019",
             "2019",
             "2019",
             "2021",
             "2021",
             "2021",
             "2021",
             "2021",
             "2022",
             "2022",
             "2023",
             "2023",
             "2022",
             "2011",
             "2009",
             "2015",
             "2017",
             "2019",
             "2019",
             "2020",
             "2021",
             "2020",
             "2021",
             "2020",
             "2022",
             "2021",
             "2022",
             "2022",
             "2023",
             "2020",
             "2021",
             "2022",
             "2023",
             "2023",
             "2023",
             "2020",
             "2021",
             "2022",
             "2023",
             "2016",
             "2020",
             "2023",
             "2017",
             "2022",
             "2021",
             "2023",
             "2016",
             "2019",
             "2023",
             "2023",
             "2023",
             "2018",
             "2019",
             "2019",
             "2020",
             "2023",
             "2022",
             "2023",
             "2020",
             "2023",
             "2023",
             "2023",
             "2023",
             "2021",
             "2023",
             "2023",
             "2004",
             "2018",
             "2018",
             "2019",
             "2021",
             "2021",
             "2022",
             "2023",
             "2022",
             "2023",
             "2023",
             
             
             ];
             

var drama = document.getElementById("ctbwld");
    for(let x=0; x<ctwl.length; x++){
        var row = drama.insertRow(-1);
        var cell1 = row.insertCell(0);
        var cell2 = row.insertCell(1);
        var cell3 = row.insertCell(2);
        
        cell2.style.width = "25%";
        cell2.style.textAlign = "center";
        cell3.style.textAlign = "center";
        
        cell1.innerHTML = ctwl[x];
        cell2.innerHTML = ccwl[x];
        cell3.innerHTML = cywl[x];
    }
}



function sortCTable(n) {
            var table, rows, switching, i, x, y, shouldSwitch, dir, switchcount = 0;
            table = document.getElementById("ctbwld");
            switching = true;
            dir = "asc";
            while (switching) {
                switching = false;
                rows = table.rows;
                for (i = 1; i < (rows.length - 1); i++) {
                    shouldSwitch = false;
                  